language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PACKAGE=utop
  matrix:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
  
#Power jobs added

  - OCAML_VERSION=4.03
    arch: ppc64le
  - OCAML_VERSION=4.04
    arch: ppc64le
  - OCAML_VERSION=4.05
    arch: ppc64le
  - OCAML_VERSION=4.06
    arch: ppc64le
  - OCAML_VERSION=4.07
    arch: ppc64le
  - OCAML_VERSION=4.08
    arch: ppc64le
  - OCAML_VERSION=4.09
    arch: ppc64le
  - OCAML_VERSION=4.10
    arch: ppc64le
  - OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
    arch: ppc64le
  
  
os:
  - linux
  - osx
